name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3.6.0
    - name: Get Cargo target
      run: rustup component add rust-src llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Install bootimage
      run: cargo install bootimage
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
